title: Xinqiao Zhang # your name (or website title) here 张新乔
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am upcoming final year Computer Engineering PhD student and some of my interests are adversarial machine learning, hardware trojan and hardware design & acceleration.
  <br><br>
  I am a big fan of high tech and crazy about latest technology
  <br><br>
  <a href="https://www.linkedin.com/in/xinqiaozhang">View My LinkedIn Profile</a> 
  <br><br> 
  <a href="pdf/Resume_Xinqiao_Zhang.pdf">View My Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-149369516-1 # your Google Analytics tracking ID here 211905412
