title: Xinqiao Zhang
logo: "/images/xinqiao1008.jpeg?raw=true"
description: >
  Senior Machine Learning Scientist at CoreLogic
  <br><br>
  Specializing in GenAI, Deep Learning, and Trustworthy ML
  <br><br>
  <a href="https://www.linkedin.com/in/xinqiaozhang">LinkedIn</a> |
  <a href="pdf/CV_Xinqiao_1024.pdf">Resume</a> |
  <a href="https://github.com/zhangxinqiao-ch">GitHub</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

# SEO settings
author: Xinqiao Zhang
twitter:
  username: 
  card: summary
social:
  name: Xinqiao Zhang
  links:
    - https://www.linkedin.com/in/xinqiaozhang
    - https://github.com/zhangxinqiao-ch

google_analytics: UA-149369516-1
